name = "Inpu"
description = "A modified version of Anpu, which is a port of the Hugo Anubis theme"
license = "MIT"
homepage = "https://github.com/wdv4758h/inpu-zola-theme"
# The minimum version of Zola required
min_version = "0.13.0"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
inpu_date_format = "%e %B %Y"
inpu_menu_links = []

# The theme author info: you!
[author]
name = "Chiu-Hsiang Hsu"
homepage = "https://github.com/wdv4758h/"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
name = "Rostislav Raykov"
homepage = "https://zbrox.com"
repo = "https://github.com/zbrox/anpu-zola-theme"
